// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wahaha.API.Data;

#nullable disable

namespace wahaha.API.Migrations
{
    [DbContext(typeof(WahahaDbContext))]
    [Migration("20260404023346_UpdateUserEmails")]
    partial class UpdateUserEmails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wahaha.API.Models.Domain.AvatarItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<int>("Cost")
                        .HasColumnType("int")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PreviewAssetUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("preview_asset_url");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rarity");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slot");

                    b.HasKey("ItemId");

                    b.ToTable("avatar_items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Category = "hat",
                            Cost = 150,
                            Description = "A pointy purple hat with golden stars",
                            IsAvailable = true,
                            Name = "Wizard Hat",
                            PreviewAssetUrl = "/assets/hats/hat_wizard.png",
                            Rarity = "RARE",
                            Slot = "HEAD"
                        },
                        new
                        {
                            ItemId = 2,
                            Category = "outfit",
                            Cost = 500,
                            Description = "Full astronaut gear with visor",
                            IsAvailable = true,
                            Name = "Space Suit",
                            PreviewAssetUrl = "/assets/outfits/suit_space.png",
                            Rarity = "EPIC",
                            Slot = "BODY"
                        },
                        new
                        {
                            ItemId = 3,
                            Category = "accessory",
                            Cost = 1200,
                            Description = "A glowing golden blade of champions",
                            IsAvailable = true,
                            Name = "Golden Sword",
                            PreviewAssetUrl = "/assets/accessories/sword_gold.png",
                            Rarity = "LEGENDARY",
                            Slot = "HAND"
                        },
                        new
                        {
                            ItemId = 4,
                            Category = "hat",
                            Cost = 40,
                            Description = "Soft pink ears with white fluff",
                            IsAvailable = true,
                            Name = "Bunny Ears",
                            PreviewAssetUrl = "/assets/hats/ears_bunny.png",
                            Rarity = "COMMON",
                            Slot = "HEAD"
                        },
                        new
                        {
                            ItemId = 5,
                            Category = "outfit",
                            Cost = 80,
                            Description = "A worn but trusty traveler's cloak",
                            IsAvailable = true,
                            Name = "Adventurer Cloak",
                            PreviewAssetUrl = "/assets/outfits/cloak_adventurer.png",
                            Rarity = "UNCOMMON",
                            Slot = "BODY"
                        },
                        new
                        {
                            ItemId = 6,
                            Category = "accessory",
                            Cost = 25,
                            Description = "Retro 8-bit style sunglasses",
                            IsAvailable = true,
                            Name = "Pixel Shades",
                            PreviewAssetUrl = "/assets/accessories/shades_pixel.png",
                            Rarity = "COMMON",
                            Slot = "FACE"
                        },
                        new
                        {
                            ItemId = 7,
                            Category = "back",
                            Cost = 1500,
                            Description = "Massive fire-breathing dragon wings",
                            IsAvailable = true,
                            Name = "Dragon Wings",
                            PreviewAssetUrl = "/assets/back/wings_dragon.png",
                            Rarity = "LEGENDARY",
                            Slot = "BACK"
                        },
                        new
                        {
                            ItemId = 8,
                            Category = "hat",
                            Cost = 35,
                            Description = "A delicate crown of wildflowers",
                            IsAvailable = true,
                            Name = "Flower Crown",
                            PreviewAssetUrl = "/assets/hats/crown_flower.png",
                            Rarity = "COMMON",
                            Slot = "HEAD"
                        },
                        new
                        {
                            ItemId = 9,
                            Category = "outfit",
                            Cost = 200,
                            Description = "Stealthy all-black ninja attire",
                            IsAvailable = true,
                            Name = "Ninja Outfit",
                            PreviewAssetUrl = "/assets/outfits/outfit_ninja.png",
                            Rarity = "RARE",
                            Slot = "BODY"
                        },
                        new
                        {
                            ItemId = 10,
                            Category = "accessory",
                            Cost = 600,
                            Description = "A glowing staff crackling with energy",
                            IsAvailable = true,
                            Name = "Magic Staff",
                            PreviewAssetUrl = "/assets/accessories/staff_magic.png",
                            Rarity = "EPIC",
                            Slot = "HAND"
                        },
                        new
                        {
                            ItemId = 11,
                            Category = "back",
                            Cost = 120,
                            Description = "A red cape that billows heroically",
                            IsAvailable = true,
                            Name = "Cape of Valor",
                            PreviewAssetUrl = "/assets/back/cape_valor.png",
                            Rarity = "UNCOMMON",
                            Slot = "BACK"
                        },
                        new
                        {
                            ItemId = 12,
                            Category = "hat",
                            Cost = 450,
                            Description = "A sleek metallic robot head piece",
                            IsAvailable = true,
                            Name = "Robot Helmet",
                            PreviewAssetUrl = "/assets/hats/helmet_robot.png",
                            Rarity = "EPIC",
                            Slot = "HEAD"
                        },
                        new
                        {
                            ItemId = 13,
                            Category = "outfit",
                            Cost = 30,
                            Description = "A comfy everyday hoodie",
                            IsAvailable = true,
                            Name = "Casual Hoodie",
                            PreviewAssetUrl = "/assets/outfits/hoodie_casual.png",
                            Rarity = "COMMON",
                            Slot = "BODY"
                        },
                        new
                        {
                            ItemId = 14,
                            Category = "hat",
                            Cost = 90,
                            Description = "A classic tricorn pirate hat",
                            IsAvailable = true,
                            Name = "Pirate Hat",
                            PreviewAssetUrl = "/assets/hats/hat_pirate.png",
                            Rarity = "UNCOMMON",
                            Slot = "HEAD"
                        },
                        new
                        {
                            ItemId = 15,
                            Category = "accessory",
                            Cost = 180,
                            Description = "A shield engraved with completed quests",
                            IsAvailable = true,
                            Name = "Shield of Tasks",
                            PreviewAssetUrl = "/assets/accessories/shield_tasks.png",
                            Rarity = "RARE",
                            Slot = "HAND"
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Minigame", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("difficulty");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("MaxPointsReward")
                        .HasColumnType("int")
                        .HasColumnName("max_points_reward");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("int")
                        .HasColumnName("unlock_level");

                    b.HasKey("GameId");

                    b.ToTable("minigames");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Description = "Solve math problems as fast as you can.",
                            Difficulty = "EASY",
                            DurationSeconds = 60,
                            MaxPointsReward = 100,
                            Name = "Math Blitz",
                            Type = "quiz",
                            UnlockLevel = 1
                        },
                        new
                        {
                            GameId = 2,
                            Description = "Unscramble the letters to form words.",
                            Difficulty = "EASY",
                            DurationSeconds = 90,
                            MaxPointsReward = 120,
                            Name = "Word Scramble",
                            Type = "puzzle",
                            UnlockLevel = 1
                        },
                        new
                        {
                            GameId = 3,
                            Description = "Answer trivia questions before time runs out.",
                            Difficulty = "MEDIUM",
                            DurationSeconds = 120,
                            MaxPointsReward = 200,
                            Name = "Trivia Rush",
                            Type = "quiz",
                            UnlockLevel = 3
                        },
                        new
                        {
                            GameId = 4,
                            Description = "Navigate a platformer to reach the goal.",
                            Difficulty = "MEDIUM",
                            DurationSeconds = 180,
                            MaxPointsReward = 250,
                            Name = "Pixel Jumper",
                            Type = "platformer",
                            UnlockLevel = 5
                        },
                        new
                        {
                            GameId = 5,
                            Description = "Test your luck with coin flips.",
                            Difficulty = "EASY",
                            DurationSeconds = 30,
                            MaxPointsReward = 150,
                            Name = "Coin Flip Frenzy",
                            Type = "chance",
                            UnlockLevel = 1
                        },
                        new
                        {
                            GameId = 6,
                            Description = "Classic arcade-style action.",
                            Difficulty = "HARD",
                            DurationSeconds = 120,
                            MaxPointsReward = 300,
                            Name = "Arcade Fever",
                            Type = "arcade",
                            UnlockLevel = 7
                        },
                        new
                        {
                            GameId = 7,
                            Description = "Compete with others in a trivia showdown.",
                            Difficulty = "HARD",
                            DurationSeconds = 300,
                            MaxPointsReward = 400,
                            Name = "Team Trivia",
                            Type = "coop",
                            UnlockLevel = 10
                        },
                        new
                        {
                            GameId = 8,
                            Description = "Connect and challenge friends.",
                            Difficulty = "EASY",
                            DurationSeconds = 60,
                            MaxPointsReward = 180,
                            Name = "Social Shuffle",
                            Type = "social",
                            UnlockLevel = 2
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.MinigameSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("outcome");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("played_at");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("points_earned");

                    b.Property<int?>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("minigame_sessions");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.PointTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("point_transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 500,
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Task completion bonus",
                            SourceType = "task",
                            Type = "EARN",
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 300,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minigame reward",
                            SourceType = "minigame",
                            Type = "EARN",
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            TransactionId = 3,
                            Amount = 180,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Purchased Shield of Tasks",
                            SourceType = "shop_item",
                            Type = "SPEND",
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            TransactionId = 4,
                            Amount = 600,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minigame reward",
                            SourceType = "minigame",
                            Type = "EARN",
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            TransactionId = 5,
                            Amount = 400,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Streak milestone bonus",
                            SourceType = "streak",
                            Type = "EARN",
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            TransactionId = 6,
                            Amount = 600,
                            CreatedAt = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Purchased Magic Staff",
                            SourceType = "shop_item",
                            Type = "SPEND",
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            TransactionId = 7,
                            Amount = 200,
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Legendary item achievement",
                            SourceType = "achievement",
                            Type = "BONUS",
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            TransactionId = 8,
                            Amount = 350,
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Task completion bonus",
                            SourceType = "task",
                            Type = "EARN",
                            UserId = new Guid("60892566-964c-4cdd-b9d1-f067981cd271")
                        },
                        new
                        {
                            TransactionId = 9,
                            Amount = 210,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minigame reward",
                            SourceType = "minigame",
                            Type = "EARN",
                            UserId = new Guid("60892566-964c-4cdd-b9d1-f067981cd271")
                        },
                        new
                        {
                            TransactionId = 10,
                            Amount = 200,
                            CreatedAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Task completion bonus",
                            SourceType = "task",
                            Type = "EARN",
                            UserId = new Guid("ea80e4bc-017d-4729-99d3-29ad8a5d9b47")
                        },
                        new
                        {
                            TransactionId = 11,
                            Amount = 110,
                            CreatedAt = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minigame reward",
                            SourceType = "minigame",
                            Type = "EARN",
                            UserId = new Guid("ea80e4bc-017d-4729-99d3-29ad8a5d9b47")
                        },
                        new
                        {
                            TransactionId = 12,
                            Amount = 50,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tutorial completion reward",
                            SourceType = "task",
                            Type = "EARN",
                            UserId = new Guid("80b6c179-8747-4a29-b112-7d774871a435")
                        },
                        new
                        {
                            TransactionId = 13,
                            Amount = 40,
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First minigame reward",
                            SourceType = "minigame",
                            Type = "EARN",
                            UserId = new Guid("80b6c179-8747-4a29-b112-7d774871a435")
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Streak", b =>
                {
                    b.Property<int>("StreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("streak_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StreakId"));

                    b.Property<decimal>("BonusMultiplier")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("bonus_multiplier");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("int")
                        .HasColumnName("current_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_activity_date");

                    b.Property<int>("LongestCount")
                        .HasColumnType("int")
                        .HasColumnName("longest_count");

                    b.Property<string>("StreakType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("streak_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("StreakId");

                    b.HasIndex("UserId");

                    b.ToTable("streaks");

                    b.HasData(
                        new
                        {
                            StreakId = 1,
                            BonusMultiplier = 1.8m,
                            CurrentCount = 14,
                            IsActive = true,
                            LastActivityDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 21,
                            StreakType = "daily_login",
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            StreakId = 2,
                            BonusMultiplier = 1.5m,
                            CurrentCount = 7,
                            IsActive = true,
                            LastActivityDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 14,
                            StreakType = "daily_task",
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            StreakId = 3,
                            BonusMultiplier = 2.0m,
                            CurrentCount = 30,
                            IsActive = true,
                            LastActivityDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 45,
                            StreakType = "daily_login",
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            StreakId = 4,
                            BonusMultiplier = 1.2m,
                            CurrentCount = 5,
                            IsActive = true,
                            LastActivityDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 10,
                            StreakType = "daily_login",
                            UserId = new Guid("60892566-964c-4cdd-b9d1-f067981cd271")
                        },
                        new
                        {
                            StreakId = 5,
                            BonusMultiplier = 1.2m,
                            CurrentCount = 3,
                            IsActive = true,
                            LastActivityDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 7,
                            StreakType = "daily_login",
                            UserId = new Guid("ea80e4bc-017d-4729-99d3-29ad8a5d9b47")
                        },
                        new
                        {
                            StreakId = 6,
                            BonusMultiplier = 1.0m,
                            CurrentCount = 1,
                            IsActive = true,
                            LastActivityDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 1,
                            StreakType = "daily_login",
                            UserId = new Guid("80b6c179-8747-4a29-b112-7d774871a435")
                        },
                        new
                        {
                            StreakId = 7,
                            BonusMultiplier = 1.0m,
                            CurrentCount = 0,
                            IsActive = false,
                            LastActivityDate = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 0,
                            StreakType = "daily_login",
                            UserId = new Guid("d5b63d3e-6049-44ed-92df-69560148f8a3")
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Task", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("task_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit")
                        .HasColumnName("is_recurring");

                    b.Property<int>("PointValue")
                        .HasColumnType("int")
                        .HasColumnName("point_value");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("priority");

                    b.Property<string>("RecurrenceRule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("recurrence_rule");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            TaskId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Category = "Learning",
                            CompletedAt = new DateTime(2026, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRecurring = true,
                            PointValue = 50,
                            Priority = "HIGH",
                            RecurrenceRule = "daily",
                            Status = "completed",
                            Title = "Complete daily quiz",
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            TaskId = new Guid("b0000001-0000-0000-0000-000000000002"),
                            Category = "Gaming",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRecurring = false,
                            PointValue = 100,
                            Priority = "MEDIUM",
                            Status = "in_progress",
                            Title = "Win 3 minigames",
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            TaskId = new Guid("b0000002-0000-0000-0000-000000000001"),
                            Category = "Progression",
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRecurring = false,
                            PointValue = 200,
                            Priority = "HIGH",
                            Status = "pending",
                            Title = "Reach level 13",
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            TaskId = new Guid("b0000002-0000-0000-0000-000000000002"),
                            Category = "Collection",
                            CompletedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRecurring = false,
                            PointValue = 75,
                            Priority = "MEDIUM",
                            Status = "completed",
                            Title = "Equip a legendary item",
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            TaskId = new Guid("b0000003-0000-0000-0000-000000000001"),
                            Category = "Productivity",
                            CreatedAt = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRecurring = false,
                            PointValue = 120,
                            Priority = "HIGH",
                            Status = "in_progress",
                            Title = "Complete 5 tasks",
                            UserId = new Guid("60892566-964c-4cdd-b9d1-f067981cd271")
                        },
                        new
                        {
                            TaskId = new Guid("b0000004-0000-0000-0000-000000000001"),
                            Category = "Gaming",
                            CreatedAt = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRecurring = false,
                            PointValue = 25,
                            Priority = "LOW",
                            Status = "pending",
                            Title = "Play a minigame",
                            UserId = new Guid("ea80e4bc-017d-4729-99d3-29ad8a5d9b47")
                        },
                        new
                        {
                            TaskId = new Guid("b0000005-0000-0000-0000-000000000001"),
                            Category = "Onboarding",
                            CompletedAt = new DateTime(2026, 3, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRecurring = false,
                            PointValue = 50,
                            Priority = "CRITICAL",
                            Status = "completed",
                            Title = "Complete tutorial",
                            UserId = new Guid("80b6c179-8747-4a29-b112-7d774871a435")
                        },
                        new
                        {
                            TaskId = new Guid("b0000006-0000-0000-0000-000000000001"),
                            Category = "Onboarding",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRecurring = false,
                            PointValue = 30,
                            Priority = "CRITICAL",
                            Status = "pending",
                            Title = "Set up your profile",
                            UserId = new Guid("d5b63d3e-6049-44ed-92df-69560148f8a3")
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.UserInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("acquired_at");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit")
                        .HasColumnName("is_equipped");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("InventoryId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("user_inventory");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            AcquiredAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 1,
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            InventoryId = 2,
                            AcquiredAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = false,
                            ItemId = 4,
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            InventoryId = 3,
                            AcquiredAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 9,
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            InventoryId = 4,
                            AcquiredAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 15,
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            InventoryId = 5,
                            AcquiredAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 11,
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            InventoryId = 6,
                            AcquiredAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 6,
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3")
                        },
                        new
                        {
                            InventoryId = 7,
                            AcquiredAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 12,
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            InventoryId = 8,
                            AcquiredAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 2,
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            InventoryId = 9,
                            AcquiredAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 10,
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            InventoryId = 10,
                            AcquiredAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 7,
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            InventoryId = 11,
                            AcquiredAt = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 6,
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            InventoryId = 12,
                            AcquiredAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = false,
                            ItemId = 3,
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b")
                        },
                        new
                        {
                            InventoryId = 13,
                            AcquiredAt = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 14,
                            UserId = new Guid("60892566-964c-4cdd-b9d1-f067981cd271")
                        },
                        new
                        {
                            InventoryId = 14,
                            AcquiredAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 5,
                            UserId = new Guid("60892566-964c-4cdd-b9d1-f067981cd271")
                        },
                        new
                        {
                            InventoryId = 15,
                            AcquiredAt = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 15,
                            UserId = new Guid("60892566-964c-4cdd-b9d1-f067981cd271")
                        },
                        new
                        {
                            InventoryId = 16,
                            AcquiredAt = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 8,
                            UserId = new Guid("ea80e4bc-017d-4729-99d3-29ad8a5d9b47")
                        },
                        new
                        {
                            InventoryId = 17,
                            AcquiredAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 13,
                            UserId = new Guid("ea80e4bc-017d-4729-99d3-29ad8a5d9b47")
                        },
                        new
                        {
                            InventoryId = 18,
                            AcquiredAt = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 11,
                            UserId = new Guid("ea80e4bc-017d-4729-99d3-29ad8a5d9b47")
                        },
                        new
                        {
                            InventoryId = 19,
                            AcquiredAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 4,
                            UserId = new Guid("80b6c179-8747-4a29-b112-7d774871a435")
                        },
                        new
                        {
                            InventoryId = 20,
                            AcquiredAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEquipped = true,
                            ItemId = 13,
                            UserId = new Guid("80b6c179-8747-4a29-b112-7d774871a435")
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("int")
                        .HasColumnName("current_balance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("TotalPointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("total_points_earned");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.Property<int>("Xp")
                        .HasColumnType("int")
                        .HasColumnName("xp");

                    b.HasKey("UserId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ea80e4bc-017d-4729-99d3-29ad8a5d9b47"),
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 310,
                            Email = "dailydragon+test@wahaha.com",
                            Level = 4,
                            TotalPointsEarned = 310,
                            Username = "DailyDragon",
                            Xp = 1200
                        },
                        new
                        {
                            UserId = new Guid("9e8e1aa6-273c-48c3-8634-56b630d6f3e3"),
                            CreatedAt = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 200,
                            Email = "questknight+test@wahaha.com",
                            Level = 9,
                            TotalPointsEarned = 820,
                            Username = "QuestKnight",
                            Xp = 3300
                        },
                        new
                        {
                            UserId = new Guid("d5b63d3e-6049-44ed-92df-69560148f8a3"),
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 0,
                            Email = "shadowfox+test@wahaha.com",
                            Level = 1,
                            TotalPointsEarned = 0,
                            Username = "ShadowFox",
                            Xp = 0
                        },
                        new
                        {
                            UserId = new Guid("80b6c179-8747-4a29-b112-7d774871a435"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 90,
                            Email = "leveluplila+test@wahaha.com",
                            Level = 2,
                            TotalPointsEarned = 90,
                            Username = "LevelUpLila",
                            Xp = 300
                        },
                        new
                        {
                            UserId = new Guid("8e43c4d2-8381-44c7-808c-8f4c98d8d57b"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 380,
                            Email = "pixelqueen+test@wahaha.com",
                            Level = 12,
                            TotalPointsEarned = 1240,
                            Username = "PixelQueen",
                            Xp = 4800
                        },
                        new
                        {
                            UserId = new Guid("60892566-964c-4cdd-b9d1-f067981cd271"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 560,
                            Email = "taskmaster9+test@wahaha.com",
                            Level = 6,
                            TotalPointsEarned = 560,
                            Username = "TaskMaster9",
                            Xp = 2100
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.MinigameSession", b =>
                {
                    b.HasOne("wahaha.API.Models.Domain.Minigame", "Minigame")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wahaha.API.Models.Domain.Users", "User")
                        .WithMany("MinigameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minigame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.PointTransaction", b =>
                {
                    b.HasOne("wahaha.API.Models.Domain.Users", "User")
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Streak", b =>
                {
                    b.HasOne("wahaha.API.Models.Domain.Users", "User")
                        .WithMany("Streaks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Task", b =>
                {
                    b.HasOne("wahaha.API.Models.Domain.Users", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.UserInventory", b =>
                {
                    b.HasOne("wahaha.API.Models.Domain.AvatarItem", "AvatarItem")
                        .WithMany("UserInventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wahaha.API.Models.Domain.Users", "User")
                        .WithMany("Inventory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvatarItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.AvatarItem", b =>
                {
                    b.Navigation("UserInventories");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Minigame", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Users", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("MinigameSessions");

                    b.Navigation("PointTransactions");

                    b.Navigation("Streaks");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
