// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wahaha.API.Data;

#nullable disable

namespace wahaha.API.Migrations
{
    [DbContext(typeof(WahahaDbContext))]
    [Migration("20260331195845_Seeding Data")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wahaha.API.Models.Domain.AvatarItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<int>("Cost")
                        .HasColumnType("int")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PreviewAssetUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("preview_asset_url");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rarity");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slot");

                    b.HasKey("ItemId");

                    b.ToTable("avatar_items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Category = "Hat",
                            Cost = 50,
                            Description = "A simple starter cap.",
                            IsAvailable = true,
                            Name = "Rookie Cap",
                            Rarity = "COMMON",
                            Slot = "HEAD"
                        },
                        new
                        {
                            ItemId = 2,
                            Category = "Hat",
                            Cost = 300,
                            Description = "A tall pointy hat for the wise.",
                            IsAvailable = true,
                            Name = "Wizard Hat",
                            Rarity = "RARE",
                            Slot = "HEAD"
                        },
                        new
                        {
                            ItemId = 3,
                            Category = "Hat",
                            Cost = 2000,
                            Description = "Only the best earn this crown.",
                            IsAvailable = true,
                            Name = "Crown of Champions",
                            Rarity = "LEGENDARY",
                            Slot = "HEAD"
                        },
                        new
                        {
                            ItemId = 4,
                            Category = "Accessory",
                            Cost = 40,
                            Description = "Classic round frames.",
                            IsAvailable = true,
                            Name = "Round Glasses",
                            Rarity = "COMMON",
                            Slot = "FACE"
                        },
                        new
                        {
                            ItemId = 5,
                            Category = "Accessory",
                            Cost = 150,
                            Description = "8-bit style sunglasses.",
                            IsAvailable = true,
                            Name = "Pixel Shades",
                            Rarity = "UNCOMMON",
                            Slot = "FACE"
                        },
                        new
                        {
                            ItemId = 6,
                            Category = "Accessory",
                            Cost = 800,
                            Description = "A sleek futuristic visor.",
                            IsAvailable = true,
                            Name = "Cyberpunk Visor",
                            Rarity = "EPIC",
                            Slot = "FACE"
                        },
                        new
                        {
                            ItemId = 7,
                            Category = "Shirt",
                            Cost = 30,
                            Description = "A plain comfortable shirt.",
                            IsAvailable = true,
                            Name = "Basic Tee",
                            Rarity = "COMMON",
                            Slot = "BODY"
                        },
                        new
                        {
                            ItemId = 8,
                            Category = "Shirt",
                            Cost = 120,
                            Description = "Cozy and casual.",
                            IsAvailable = true,
                            Name = "Hoodie",
                            Rarity = "UNCOMMON",
                            Slot = "BODY"
                        },
                        new
                        {
                            ItemId = 9,
                            Category = "Jacket",
                            Cost = 500,
                            Description = "Stand out with this glowing jacket.",
                            IsAvailable = true,
                            Name = "Neon Jacket",
                            Rarity = "RARE",
                            Slot = "BODY"
                        },
                        new
                        {
                            ItemId = 10,
                            Category = "Armor",
                            Cost = 3000,
                            Description = "Forged from dragon scales.",
                            IsAvailable = true,
                            Name = "Dragon Armor",
                            Rarity = "LEGENDARY",
                            Slot = "BODY"
                        },
                        new
                        {
                            ItemId = 11,
                            Category = "Gloves",
                            Cost = 35,
                            Description = "Edgy and practical.",
                            IsAvailable = true,
                            Name = "Fingerless Gloves",
                            Rarity = "COMMON",
                            Slot = "HAND"
                        },
                        new
                        {
                            ItemId = 12,
                            Category = "Gloves",
                            Cost = 900,
                            Description = "Feel unstoppable.",
                            IsAvailable = true,
                            Name = "Power Gauntlets",
                            Rarity = "EPIC",
                            Slot = "HAND"
                        },
                        new
                        {
                            ItemId = 13,
                            Category = "Back",
                            Cost = 60,
                            Description = "A handy little pack.",
                            IsAvailable = true,
                            Name = "Mini Backpack",
                            Rarity = "COMMON",
                            Slot = "BACK"
                        },
                        new
                        {
                            ItemId = 14,
                            Category = "Back",
                            Cost = 5000,
                            Description = "Ethereal wings of light.",
                            IsAvailable = true,
                            Name = "Angel Wings",
                            Rarity = "LEGENDARY",
                            Slot = "BACK"
                        },
                        new
                        {
                            ItemId = 15,
                            Category = "Shoes",
                            Cost = 50,
                            Description = "Fresh kicks.",
                            IsAvailable = true,
                            Name = "Sneakers",
                            Rarity = "COMMON",
                            Slot = "FEET"
                        },
                        new
                        {
                            ItemId = 16,
                            Category = "Shoes",
                            Cost = 1200,
                            Description = "Boots with built-in thrusters.",
                            IsAvailable = true,
                            Name = "Rocket Boots",
                            Rarity = "EPIC",
                            Slot = "FEET"
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Minigame", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("difficulty");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("MaxPointsReward")
                        .HasColumnType("int")
                        .HasColumnName("max_points_reward");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("int")
                        .HasColumnName("unlock_level");

                    b.HasKey("GameId");

                    b.ToTable("minigames");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Description = "Solve math problems as fast as you can.",
                            Difficulty = "EASY",
                            DurationSeconds = 60,
                            MaxPointsReward = 100,
                            Name = "Math Blitz",
                            Type = "quiz",
                            UnlockLevel = 1
                        },
                        new
                        {
                            GameId = 2,
                            Description = "Unscramble the letters to form words.",
                            Difficulty = "EASY",
                            DurationSeconds = 90,
                            MaxPointsReward = 120,
                            Name = "Word Scramble",
                            Type = "puzzle",
                            UnlockLevel = 1
                        },
                        new
                        {
                            GameId = 3,
                            Description = "Answer trivia questions before time runs out.",
                            Difficulty = "MEDIUM",
                            DurationSeconds = 120,
                            MaxPointsReward = 200,
                            Name = "Trivia Rush",
                            Type = "quiz",
                            UnlockLevel = 3
                        },
                        new
                        {
                            GameId = 4,
                            Description = "Navigate a platformer to reach the goal.",
                            Difficulty = "MEDIUM",
                            DurationSeconds = 180,
                            MaxPointsReward = 250,
                            Name = "Pixel Jumper",
                            Type = "platformer",
                            UnlockLevel = 5
                        },
                        new
                        {
                            GameId = 5,
                            Description = "Test your luck with coin flips.",
                            Difficulty = "EASY",
                            DurationSeconds = 30,
                            MaxPointsReward = 150,
                            Name = "Coin Flip Frenzy",
                            Type = "chance",
                            UnlockLevel = 1
                        },
                        new
                        {
                            GameId = 6,
                            Description = "Classic arcade-style action.",
                            Difficulty = "HARD",
                            DurationSeconds = 120,
                            MaxPointsReward = 300,
                            Name = "Arcade Fever",
                            Type = "arcade",
                            UnlockLevel = 7
                        },
                        new
                        {
                            GameId = 7,
                            Description = "Compete with others in a trivia showdown.",
                            Difficulty = "HARD",
                            DurationSeconds = 300,
                            MaxPointsReward = 400,
                            Name = "Team Trivia",
                            Type = "coop",
                            UnlockLevel = 10
                        },
                        new
                        {
                            GameId = 8,
                            Description = "Connect and challenge friends.",
                            Difficulty = "EASY",
                            DurationSeconds = 60,
                            MaxPointsReward = 180,
                            Name = "Social Shuffle",
                            Type = "social",
                            UnlockLevel = 2
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.MinigameSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("outcome");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("played_at");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("points_earned");

                    b.Property<int?>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("minigame_sessions");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.PointTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("point_transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 500,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Task completion bonus",
                            SourceType = "task",
                            Type = "EARN",
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 300,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minigame reward",
                            SourceType = "minigame",
                            Type = "EARN",
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            TransactionId = 3,
                            Amount = 700,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "7-day streak bonus",
                            SourceType = "streak",
                            Type = "EARN",
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            TransactionId = 4,
                            Amount = 300,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Purchased Wizard Hat",
                            SourceType = "shop_item",
                            Type = "SPEND",
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            TransactionId = 5,
                            Amount = 200,
                            CreatedAt = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First win achievement",
                            SourceType = "achievement",
                            Type = "BONUS",
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            TransactionId = 6,
                            Amount = 200,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Task completion bonus",
                            SourceType = "task",
                            Type = "EARN",
                            UserId = new Guid("a1b2c3d4-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            TransactionId = 7,
                            Amount = 150,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minigame reward",
                            SourceType = "minigame",
                            Type = "EARN",
                            UserId = new Guid("a1b2c3d4-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            TransactionId = 8,
                            Amount = 50,
                            CreatedAt = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Purchased Sneakers",
                            SourceType = "shop_item",
                            Type = "SPEND",
                            UserId = new Guid("a1b2c3d4-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            TransactionId = 9,
                            Amount = 400,
                            CreatedAt = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Streak milestone bonus",
                            SourceType = "streak",
                            Type = "EARN",
                            UserId = new Guid("a1b2c3d4-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            TransactionId = 10,
                            Amount = 100,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tutorial completion reward",
                            SourceType = "task",
                            Type = "EARN",
                            UserId = new Guid("a1b2c3d4-0003-0003-0003-000000000003")
                        },
                        new
                        {
                            TransactionId = 11,
                            Amount = 100,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Welcome bonus",
                            SourceType = "achievement",
                            Type = "BONUS",
                            UserId = new Guid("a1b2c3d4-0003-0003-0003-000000000003")
                        },
                        new
                        {
                            TransactionId = 12,
                            Amount = 50,
                            CreatedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Purchased Basic Tee",
                            SourceType = "shop_item",
                            Type = "SPEND",
                            UserId = new Guid("a1b2c3d4-0003-0003-0003-000000000003")
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Streak", b =>
                {
                    b.Property<int>("StreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("streak_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StreakId"));

                    b.Property<decimal>("BonusMultiplier")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("bonus_multiplier");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("int")
                        .HasColumnName("current_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_activity_date");

                    b.Property<int>("LongestCount")
                        .HasColumnType("int")
                        .HasColumnName("longest_count");

                    b.Property<string>("StreakType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("streak_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("StreakId");

                    b.HasIndex("UserId");

                    b.ToTable("streaks");

                    b.HasData(
                        new
                        {
                            StreakId = 1,
                            BonusMultiplier = 1.8m,
                            CurrentCount = 14,
                            IsActive = true,
                            LastActivityDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 21,
                            StreakType = "daily_login",
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            StreakId = 2,
                            BonusMultiplier = 1.5m,
                            CurrentCount = 7,
                            IsActive = true,
                            LastActivityDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 14,
                            StreakType = "daily_task",
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            StreakId = 3,
                            BonusMultiplier = 1.2m,
                            CurrentCount = 3,
                            IsActive = true,
                            LastActivityDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 10,
                            StreakType = "daily_login",
                            UserId = new Guid("a1b2c3d4-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            StreakId = 4,
                            BonusMultiplier = 1.0m,
                            CurrentCount = 1,
                            IsActive = true,
                            LastActivityDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LongestCount = 1,
                            StreakType = "daily_login",
                            UserId = new Guid("a1b2c3d4-0003-0003-0003-000000000003")
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Task", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("task_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit")
                        .HasColumnName("is_recurring");

                    b.Property<int>("PointValue")
                        .HasColumnType("int")
                        .HasColumnName("point_value");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("priority");

                    b.Property<string>("RecurrenceRule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("recurrence_rule");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            TaskId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Category = "Learning",
                            CompletedAt = new DateTime(2025, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Finish the daily trivia quiz.",
                            IsRecurring = true,
                            PointValue = 50,
                            Priority = "HIGH",
                            RecurrenceRule = "daily",
                            Status = "completed",
                            Title = "Complete daily quiz",
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            TaskId = new Guid("b0000001-0000-0000-0000-000000000002"),
                            Category = "Gaming",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Win any 3 minigames this week.",
                            IsRecurring = false,
                            PointValue = 100,
                            Priority = "MEDIUM",
                            Status = "in_progress",
                            Title = "Win 3 minigames",
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            TaskId = new Guid("b0000001-0000-0000-0000-000000000003"),
                            Category = "Engagement",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Log in 7 days in a row.",
                            DueDate = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRecurring = false,
                            PointValue = 150,
                            Priority = "HIGH",
                            Status = "pending",
                            Title = "Maintain 7-day streak",
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            TaskId = new Guid("b0000002-0000-0000-0000-000000000001"),
                            Category = "Shopping",
                            CompletedAt = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Purchase any item from the shop.",
                            IsRecurring = false,
                            PointValue = 30,
                            Priority = "LOW",
                            Status = "completed",
                            Title = "Buy first avatar item",
                            UserId = new Guid("a1b2c3d4-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            TaskId = new Guid("b0000002-0000-0000-0000-000000000002"),
                            Category = "Gaming",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Join a cooperative minigame session.",
                            DueDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRecurring = false,
                            PointValue = 75,
                            Priority = "MEDIUM",
                            Status = "pending",
                            Title = "Play a coop game",
                            UserId = new Guid("a1b2c3d4-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            TaskId = new Guid("b0000003-0000-0000-0000-000000000001"),
                            Category = "Onboarding",
                            CompletedAt = new DateTime(2025, 2, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Finish the onboarding tutorial.",
                            IsRecurring = false,
                            PointValue = 50,
                            Priority = "CRITICAL",
                            Status = "completed",
                            Title = "Complete tutorial",
                            UserId = new Guid("a1b2c3d4-0003-0003-0003-000000000003")
                        },
                        new
                        {
                            TaskId = new Guid("b0000003-0000-0000-0000-000000000002"),
                            Category = "Gaming",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Try out any minigame.",
                            IsRecurring = false,
                            PointValue = 25,
                            Priority = "HIGH",
                            Status = "pending",
                            Title = "Play first minigame",
                            UserId = new Guid("a1b2c3d4-0003-0003-0003-000000000003")
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.UserInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("acquired_at");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit")
                        .HasColumnName("is_equipped");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("InventoryId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("user_inventory");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("int")
                        .HasColumnName("current_balance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("TotalPointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("total_points_earned");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.Property<int>("Xp")
                        .HasColumnType("int")
                        .HasColumnName("xp");

                    b.HasKey("UserId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 800,
                            Email = "wizard@wahaha.com",
                            Level = 5,
                            TotalPointsEarned = 1500,
                            Username = "byte_wizard",
                            Xp = 4200
                        },
                        new
                        {
                            UserId = new Guid("a1b2c3d4-0002-0002-0002-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 300,
                            Email = "panda@wahaha.com",
                            Level = 3,
                            TotalPointsEarned = 750,
                            Username = "pixel_panda",
                            Xp = 1800
                        },
                        new
                        {
                            UserId = new Guid("a1b2c3d4-0003-0003-0003-000000000003"),
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 150,
                            Email = "nova@wahaha.com",
                            Level = 1,
                            TotalPointsEarned = 200,
                            Username = "nova_runner",
                            Xp = 400
                        });
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.MinigameSession", b =>
                {
                    b.HasOne("wahaha.API.Models.Domain.Minigame", "Minigame")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wahaha.API.Models.Domain.Users", "User")
                        .WithMany("MinigameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minigame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.PointTransaction", b =>
                {
                    b.HasOne("wahaha.API.Models.Domain.Users", "User")
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Streak", b =>
                {
                    b.HasOne("wahaha.API.Models.Domain.Users", "User")
                        .WithMany("Streaks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Task", b =>
                {
                    b.HasOne("wahaha.API.Models.Domain.Users", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.UserInventory", b =>
                {
                    b.HasOne("wahaha.API.Models.Domain.AvatarItem", "AvatarItem")
                        .WithMany("UserInventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wahaha.API.Models.Domain.Users", "User")
                        .WithMany("Inventory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvatarItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.AvatarItem", b =>
                {
                    b.Navigation("UserInventories");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Minigame", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("wahaha.API.Models.Domain.Users", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("MinigameSessions");

                    b.Navigation("PointTransactions");

                    b.Navigation("Streaks");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
